//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8745
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gera.com.br/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gera.com.br/", IsNullable=true)]
public partial class ArrayOfRevendedorNaturaBoliviaOut_v1 {
    
    private RevendedorNaturaBoliviaOut_v1[] registroField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Registro", IsNullable=true)]
    public RevendedorNaturaBoliviaOut_v1[] Registro {
        get {
            return this.registroField;
        }
        set {
            this.registroField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gera.com.br/")]
public partial class RevendedorNaturaBoliviaOut_v1 {
    
    private long codigoDocumentoField;
    
    private int codigoPessoaField;
    
    private int campanhaPrimeiroPedidoField;
    
    private bool campanhaPrimeiroPedidoFieldSpecified;
    
    private System.DateTime dataHoraPrimeiroPedidoField;
    
    private bool dataHoraPrimeiroPedidoFieldSpecified;
    
    private int campanhaReativacaoField;
    
    private bool campanhaReativacaoFieldSpecified;
    
    private int campanhaCessamentoField;
    
    private bool campanhaCessamentoFieldSpecified;
    
    private int quantidadeCampanhasSemPedidoField;
    
    private int codigoPapelField;
    
    private bool codigoPapelFieldSpecified;
    
    private string descricaoPapelField;
    
    private int limiteCreditoField;
    
    private bool limiteCreditoFieldSpecified;
    
    private int codigoEstruturaNivel0Field;
    
    private bool codigoEstruturaNivel0FieldSpecified;
    
    private int codigoEstruturaNivel1Field;
    
    private bool codigoEstruturaNivel1FieldSpecified;
    
    private int codigoEstruturaNivel2Field;
    
    private bool codigoEstruturaNivel2FieldSpecified;
    
    private int codigoEstruturaNivel3Field;
    
    private bool codigoEstruturaNivel3FieldSpecified;
    
    private int codigoEstruturaNivel4Field;
    
    private bool codigoEstruturaNivel4FieldSpecified;
    
    private int codigoEstruturaNivel5Field;
    
    private bool codigoEstruturaNivel5FieldSpecified;
    
    private int codigoEstruturaNivel6Field;
    
    private bool codigoEstruturaNivel6FieldSpecified;
    
    private int codigoEstruturaNivel7Field;
    
    private bool codigoEstruturaNivel7FieldSpecified;
    
    private int codigoEstruturaNivel8Field;
    
    private bool codigoEstruturaNivel8FieldSpecified;
    
    private int codigoEstruturaNivel9Field;
    
    private bool codigoEstruturaNivel9FieldSpecified;
    
    private string descricaoEstruturaNivel0Field;
    
    private string descricaoEstruturaNivel1Field;
    
    private string descricaoEstruturaNivel2Field;
    
    private string descricaoEstruturaNivel3Field;
    
    private string descricaoEstruturaNivel4Field;
    
    private string descricaoEstruturaNivel5Field;
    
    private string descricaoEstruturaNivel6Field;
    
    private string descricaoEstruturaNivel7Field;
    
    private string descricaoEstruturaNivel8Field;
    
    private string descricaoEstruturaNivel9Field;
    
    private string bloqueadoField;
    
    private string motivoBloqueioField;
    
    private int codigoUltimoPedidoField;
    
    private bool codigoUltimoPedidoFieldSpecified;
    
    private System.DateTime dataHoraCaptacaoUltimoPedidoField;
    
    private bool dataHoraCaptacaoUltimoPedidoFieldSpecified;
    
    private int codigoPessoaIndicacaoField;
    
    private bool codigoPessoaIndicacaoFieldSpecified;
    
    private string nomePessoaIndicacaoField;
    
    private string possuiPerfilComercialField;
    
    private int saldoCreditoField;
    
    private byte tipoSituacaoCompradorField;
    
    private string situacaoCompradorField;
    
    /// <comentarios/>
    public long CodigoDocumento {
        get {
            return this.codigoDocumentoField;
        }
        set {
            this.codigoDocumentoField = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoPessoa {
        get {
            return this.codigoPessoaField;
        }
        set {
            this.codigoPessoaField = value;
        }
    }
    
    /// <comentarios/>
    public int CampanhaPrimeiroPedido {
        get {
            return this.campanhaPrimeiroPedidoField;
        }
        set {
            this.campanhaPrimeiroPedidoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CampanhaPrimeiroPedidoSpecified {
        get {
            return this.campanhaPrimeiroPedidoFieldSpecified;
        }
        set {
            this.campanhaPrimeiroPedidoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime DataHoraPrimeiroPedido {
        get {
            return this.dataHoraPrimeiroPedidoField;
        }
        set {
            this.dataHoraPrimeiroPedidoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataHoraPrimeiroPedidoSpecified {
        get {
            return this.dataHoraPrimeiroPedidoFieldSpecified;
        }
        set {
            this.dataHoraPrimeiroPedidoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CampanhaReativacao {
        get {
            return this.campanhaReativacaoField;
        }
        set {
            this.campanhaReativacaoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CampanhaReativacaoSpecified {
        get {
            return this.campanhaReativacaoFieldSpecified;
        }
        set {
            this.campanhaReativacaoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CampanhaCessamento {
        get {
            return this.campanhaCessamentoField;
        }
        set {
            this.campanhaCessamentoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CampanhaCessamentoSpecified {
        get {
            return this.campanhaCessamentoFieldSpecified;
        }
        set {
            this.campanhaCessamentoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int QuantidadeCampanhasSemPedido {
        get {
            return this.quantidadeCampanhasSemPedidoField;
        }
        set {
            this.quantidadeCampanhasSemPedidoField = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoPapel {
        get {
            return this.codigoPapelField;
        }
        set {
            this.codigoPapelField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoPapelSpecified {
        get {
            return this.codigoPapelFieldSpecified;
        }
        set {
            this.codigoPapelFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoPapel {
        get {
            return this.descricaoPapelField;
        }
        set {
            this.descricaoPapelField = value;
        }
    }
    
    /// <comentarios/>
    public int LimiteCredito {
        get {
            return this.limiteCreditoField;
        }
        set {
            this.limiteCreditoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LimiteCreditoSpecified {
        get {
            return this.limiteCreditoFieldSpecified;
        }
        set {
            this.limiteCreditoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel0 {
        get {
            return this.codigoEstruturaNivel0Field;
        }
        set {
            this.codigoEstruturaNivel0Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel0Specified {
        get {
            return this.codigoEstruturaNivel0FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel0FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel1 {
        get {
            return this.codigoEstruturaNivel1Field;
        }
        set {
            this.codigoEstruturaNivel1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel1Specified {
        get {
            return this.codigoEstruturaNivel1FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel1FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel2 {
        get {
            return this.codigoEstruturaNivel2Field;
        }
        set {
            this.codigoEstruturaNivel2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel2Specified {
        get {
            return this.codigoEstruturaNivel2FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel2FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel3 {
        get {
            return this.codigoEstruturaNivel3Field;
        }
        set {
            this.codigoEstruturaNivel3Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel3Specified {
        get {
            return this.codigoEstruturaNivel3FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel3FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel4 {
        get {
            return this.codigoEstruturaNivel4Field;
        }
        set {
            this.codigoEstruturaNivel4Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel4Specified {
        get {
            return this.codigoEstruturaNivel4FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel4FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel5 {
        get {
            return this.codigoEstruturaNivel5Field;
        }
        set {
            this.codigoEstruturaNivel5Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel5Specified {
        get {
            return this.codigoEstruturaNivel5FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel5FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel6 {
        get {
            return this.codigoEstruturaNivel6Field;
        }
        set {
            this.codigoEstruturaNivel6Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel6Specified {
        get {
            return this.codigoEstruturaNivel6FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel6FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel7 {
        get {
            return this.codigoEstruturaNivel7Field;
        }
        set {
            this.codigoEstruturaNivel7Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel7Specified {
        get {
            return this.codigoEstruturaNivel7FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel7FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel8 {
        get {
            return this.codigoEstruturaNivel8Field;
        }
        set {
            this.codigoEstruturaNivel8Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel8Specified {
        get {
            return this.codigoEstruturaNivel8FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel8FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoEstruturaNivel9 {
        get {
            return this.codigoEstruturaNivel9Field;
        }
        set {
            this.codigoEstruturaNivel9Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoEstruturaNivel9Specified {
        get {
            return this.codigoEstruturaNivel9FieldSpecified;
        }
        set {
            this.codigoEstruturaNivel9FieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel0 {
        get {
            return this.descricaoEstruturaNivel0Field;
        }
        set {
            this.descricaoEstruturaNivel0Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel1 {
        get {
            return this.descricaoEstruturaNivel1Field;
        }
        set {
            this.descricaoEstruturaNivel1Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel2 {
        get {
            return this.descricaoEstruturaNivel2Field;
        }
        set {
            this.descricaoEstruturaNivel2Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel3 {
        get {
            return this.descricaoEstruturaNivel3Field;
        }
        set {
            this.descricaoEstruturaNivel3Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel4 {
        get {
            return this.descricaoEstruturaNivel4Field;
        }
        set {
            this.descricaoEstruturaNivel4Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel5 {
        get {
            return this.descricaoEstruturaNivel5Field;
        }
        set {
            this.descricaoEstruturaNivel5Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel6 {
        get {
            return this.descricaoEstruturaNivel6Field;
        }
        set {
            this.descricaoEstruturaNivel6Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel7 {
        get {
            return this.descricaoEstruturaNivel7Field;
        }
        set {
            this.descricaoEstruturaNivel7Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel8 {
        get {
            return this.descricaoEstruturaNivel8Field;
        }
        set {
            this.descricaoEstruturaNivel8Field = value;
        }
    }
    
    /// <comentarios/>
    public string DescricaoEstruturaNivel9 {
        get {
            return this.descricaoEstruturaNivel9Field;
        }
        set {
            this.descricaoEstruturaNivel9Field = value;
        }
    }
    
    /// <comentarios/>
    public string Bloqueado {
        get {
            return this.bloqueadoField;
        }
        set {
            this.bloqueadoField = value;
        }
    }
    
    /// <comentarios/>
    public string MotivoBloqueio {
        get {
            return this.motivoBloqueioField;
        }
        set {
            this.motivoBloqueioField = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoUltimoPedido {
        get {
            return this.codigoUltimoPedidoField;
        }
        set {
            this.codigoUltimoPedidoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoUltimoPedidoSpecified {
        get {
            return this.codigoUltimoPedidoFieldSpecified;
        }
        set {
            this.codigoUltimoPedidoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime DataHoraCaptacaoUltimoPedido {
        get {
            return this.dataHoraCaptacaoUltimoPedidoField;
        }
        set {
            this.dataHoraCaptacaoUltimoPedidoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataHoraCaptacaoUltimoPedidoSpecified {
        get {
            return this.dataHoraCaptacaoUltimoPedidoFieldSpecified;
        }
        set {
            this.dataHoraCaptacaoUltimoPedidoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public int CodigoPessoaIndicacao {
        get {
            return this.codigoPessoaIndicacaoField;
        }
        set {
            this.codigoPessoaIndicacaoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodigoPessoaIndicacaoSpecified {
        get {
            return this.codigoPessoaIndicacaoFieldSpecified;
        }
        set {
            this.codigoPessoaIndicacaoFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string NomePessoaIndicacao {
        get {
            return this.nomePessoaIndicacaoField;
        }
        set {
            this.nomePessoaIndicacaoField = value;
        }
    }
    
    /// <comentarios/>
    public string PossuiPerfilComercial {
        get {
            return this.possuiPerfilComercialField;
        }
        set {
            this.possuiPerfilComercialField = value;
        }
    }
    
    /// <comentarios/>
    public int SaldoCredito {
        get {
            return this.saldoCreditoField;
        }
        set {
            this.saldoCreditoField = value;
        }
    }
    
    /// <comentarios/>
    public byte TipoSituacaoComprador {
        get {
            return this.tipoSituacaoCompradorField;
        }
        set {
            this.tipoSituacaoCompradorField = value;
        }
    }
    
    /// <comentarios/>
    public string SituacaoComprador {
        get {
            return this.situacaoCompradorField;
        }
        set {
            this.situacaoCompradorField = value;
        }
    }
}
