//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioIntegracion.PadraoPruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoExportacao", Namespace="http://www.geravd.com.br/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioIntegracion.PadraoPruebas.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioIntegracion.PadraoPruebas.ArrayOfConfirmacaoDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioIntegracion.PadraoPruebas.ConfirmacaoDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioIntegracion.PadraoPruebas.RetornoImportacao))]
    public partial class RetornoExportacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataHoraField;
        
        private long CodigoTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioIntegracion.PadraoPruebas.ArrayOfString ErrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long CodigoTicket {
            get {
                return this.CodigoTicketField;
            }
            set {
                if ((this.CodigoTicketField.Equals(value) != true)) {
                    this.CodigoTicketField = value;
                    this.RaisePropertyChanged("CodigoTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CheckSum {
            get {
                return this.CheckSumField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckSumField, value) != true)) {
                    this.CheckSumField = value;
                    this.RaisePropertyChanged("CheckSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServicioIntegracion.PadraoPruebas.ArrayOfString Erros {
            get {
                return this.ErrosField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrosField, value) != true)) {
                    this.ErrosField = value;
                    this.RaisePropertyChanged("Erros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.geravd.com.br/", ItemName="DescricaoErro")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfConfirmacaoDocumento", Namespace="http://www.geravd.com.br/", ItemName="Documento")]
    [System.SerializableAttribute()]
    public class ArrayOfConfirmacaoDocumento : System.Collections.Generic.List<ServicioIntegracion.PadraoPruebas.ConfirmacaoDocumento> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmacaoDocumento", Namespace="http://www.geravd.com.br/")]
    [System.SerializableAttribute()]
    public partial class ConfirmacaoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long CodigoDocumentoField;
        
        private int SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long CodigoDocumento {
            get {
                return this.CodigoDocumentoField;
            }
            set {
                if ((this.CodigoDocumentoField.Equals(value) != true)) {
                    this.CodigoDocumentoField = value;
                    this.RaisePropertyChanged("CodigoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErroField, value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MensagemErro {
            get {
                return this.MensagemErroField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemErroField, value) != true)) {
                    this.MensagemErroField = value;
                    this.RaisePropertyChanged("MensagemErro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoImportacao", Namespace="http://www.geravd.com.br/")]
    [System.SerializableAttribute()]
    public partial class RetornoImportacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServicioIntegracion.PadraoPruebas.ArrayOfString ErrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServicioIntegracion.PadraoPruebas.ArrayOfString Erros {
            get {
                return this.ErrosField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrosField, value) != true)) {
                    this.ErrosField = value;
                    this.RaisePropertyChanged("Erros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.geravd.com.br/", ConfigurationName="PadraoPruebas.WSIntegracaoPadraoSoap")]
    public interface WSIntegracaoPadraoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ParametrosExportacao) del mensaje ExportarDadosRequest no coincide con el valor predeterminado (ExportarDados)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/ExportarDados", ReplyAction="*")]
        ServicioIntegracion.PadraoPruebas.ExportarDadosResponse ExportarDados(ServicioIntegracion.PadraoPruebas.ExportarDadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/ExportarDados", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ExportarDadosResponse> ExportarDadosAsync(ServicioIntegracion.PadraoPruebas.ExportarDadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/AdicionaConfirmacao", ReplyAction="*")]
        ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse AdicionarConfirmacaoTicket(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/AdicionaConfirmacao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse> AdicionarConfirmacaoTicketAsync(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ParametrosImportacao) del mensaje ImportarDadosRequest no coincide con el valor predeterminado (ImportarDados)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/ImportarDados", ReplyAction="*")]
        ServicioIntegracion.PadraoPruebas.ImportarDadosResponse ImportarDados(ServicioIntegracion.PadraoPruebas.ImportarDadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.geravd.com.br/ImportarDados", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ImportarDadosResponse> ImportarDadosAsync(ServicioIntegracion.PadraoPruebas.ImportarDadosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParametrosExportacao", WrapperNamespace="http://www.geravd.com.br/", IsWrapped=true)]
    public partial class ExportarDadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=0)]
        public string tokenAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=1)]
        public string interfaceIntegracao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=2)]
        public string versao;
        
        public ExportarDadosRequest() {
        }
        
        public ExportarDadosRequest(string tokenAutenticacao, string interfaceIntegracao, string versao) {
            this.tokenAutenticacao = tokenAutenticacao;
            this.interfaceIntegracao = interfaceIntegracao;
            this.versao = versao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportacaoResponse", WrapperNamespace="http://www.geravd.com.br/", IsWrapped=true)]
    public partial class ExportarDadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=0)]
        public ServicioIntegracion.PadraoPruebas.RetornoExportacao IntegracaoResult;
        
        public ExportarDadosResponse() {
        }
        
        public ExportarDadosResponse(ServicioIntegracion.PadraoPruebas.RetornoExportacao IntegracaoResult) {
            this.IntegracaoResult = IntegracaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarConfirmacaoTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParametrosConfirmacaoTicket", Namespace="http://www.geravd.com.br/", Order=0)]
        public ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequestBody Body;
        
        public AdicionarConfirmacaoTicketRequest() {
        }
        
        public AdicionarConfirmacaoTicketRequest(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.geravd.com.br/")]
    public partial class AdicionarConfirmacaoTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenAutenticacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string InterfaceIntegracao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Versao;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long CodigoTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServicioIntegracion.PadraoPruebas.ArrayOfConfirmacaoDocumento Documentos;
        
        public AdicionarConfirmacaoTicketRequestBody() {
        }
        
        public AdicionarConfirmacaoTicketRequestBody(string TokenAutenticacao, string InterfaceIntegracao, string Versao, long CodigoTicket, ServicioIntegracion.PadraoPruebas.ArrayOfConfirmacaoDocumento Documentos) {
            this.TokenAutenticacao = TokenAutenticacao;
            this.InterfaceIntegracao = InterfaceIntegracao;
            this.Versao = Versao;
            this.CodigoTicket = CodigoTicket;
            this.Documentos = Documentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdicionarConfirmacaoTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmacaoTicketResponse", Namespace="http://www.geravd.com.br/", Order=0)]
        public ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponseBody Body;
        
        public AdicionarConfirmacaoTicketResponse() {
        }
        
        public AdicionarConfirmacaoTicketResponse(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.geravd.com.br/")]
    public partial class AdicionarConfirmacaoTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProcessamentoOK;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime DataHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServicioIntegracion.PadraoPruebas.ArrayOfString Erros;
        
        public AdicionarConfirmacaoTicketResponseBody() {
        }
        
        public AdicionarConfirmacaoTicketResponseBody(bool ProcessamentoOK, System.DateTime DataHora, ServicioIntegracion.PadraoPruebas.ArrayOfString Erros) {
            this.ProcessamentoOK = ProcessamentoOK;
            this.DataHora = DataHora;
            this.Erros = Erros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParametrosImportacao", WrapperNamespace="http://www.geravd.com.br/", IsWrapped=true)]
    public partial class ImportarDadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=0)]
        public string tokenAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=1)]
        public string interfaceIntegracao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=2)]
        public string versao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=3)]
        public string CodigoTicket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=4)]
        public string Ticket;
        
        public ImportarDadosRequest() {
        }
        
        public ImportarDadosRequest(string tokenAutenticacao, string interfaceIntegracao, string versao, string CodigoTicket, string Ticket) {
            this.tokenAutenticacao = tokenAutenticacao;
            this.interfaceIntegracao = interfaceIntegracao;
            this.versao = versao;
            this.CodigoTicket = CodigoTicket;
            this.Ticket = Ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportacaoResponse", WrapperNamespace="http://www.geravd.com.br/", IsWrapped=true)]
    public partial class ImportarDadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.geravd.com.br/", Order=0)]
        public ServicioIntegracion.PadraoPruebas.RetornoImportacao IntegracaoResult;
        
        public ImportarDadosResponse() {
        }
        
        public ImportarDadosResponse(ServicioIntegracion.PadraoPruebas.RetornoImportacao IntegracaoResult) {
            this.IntegracaoResult = IntegracaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntegracaoPadraoSoapChannel : ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntegracaoPadraoSoapClient : System.ServiceModel.ClientBase<ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap>, ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap {
        
        public WSIntegracaoPadraoSoapClient() {
        }
        
        public WSIntegracaoPadraoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntegracaoPadraoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracaoPadraoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegracaoPadraoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioIntegracion.PadraoPruebas.ExportarDadosResponse ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.ExportarDados(ServicioIntegracion.PadraoPruebas.ExportarDadosRequest request) {
            return base.Channel.ExportarDados(request);
        }
        
        public ServicioIntegracion.PadraoPruebas.RetornoExportacao ExportarDados(string tokenAutenticacao, string interfaceIntegracao, string versao) {
            ServicioIntegracion.PadraoPruebas.ExportarDadosRequest inValue = new ServicioIntegracion.PadraoPruebas.ExportarDadosRequest();
            inValue.tokenAutenticacao = tokenAutenticacao;
            inValue.interfaceIntegracao = interfaceIntegracao;
            inValue.versao = versao;
            ServicioIntegracion.PadraoPruebas.ExportarDadosResponse retVal = ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).ExportarDados(inValue);
            return retVal.IntegracaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ExportarDadosResponse> ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.ExportarDadosAsync(ServicioIntegracion.PadraoPruebas.ExportarDadosRequest request) {
            return base.Channel.ExportarDadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ExportarDadosResponse> ExportarDadosAsync(string tokenAutenticacao, string interfaceIntegracao, string versao) {
            ServicioIntegracion.PadraoPruebas.ExportarDadosRequest inValue = new ServicioIntegracion.PadraoPruebas.ExportarDadosRequest();
            inValue.tokenAutenticacao = tokenAutenticacao;
            inValue.interfaceIntegracao = interfaceIntegracao;
            inValue.versao = versao;
            return ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).ExportarDadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.AdicionarConfirmacaoTicket(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest request) {
            return base.Channel.AdicionarConfirmacaoTicket(request);
        }
        
        public bool AdicionarConfirmacaoTicket(string TokenAutenticacao, string InterfaceIntegracao, string Versao, long CodigoTicket, ServicioIntegracion.PadraoPruebas.ArrayOfConfirmacaoDocumento Documentos, out System.DateTime DataHora, out ServicioIntegracion.PadraoPruebas.ArrayOfString Erros) {
            ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest inValue = new ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest();
            inValue.Body = new ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequestBody();
            inValue.Body.TokenAutenticacao = TokenAutenticacao;
            inValue.Body.InterfaceIntegracao = InterfaceIntegracao;
            inValue.Body.Versao = Versao;
            inValue.Body.CodigoTicket = CodigoTicket;
            inValue.Body.Documentos = Documentos;
            ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse retVal = ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).AdicionarConfirmacaoTicket(inValue);
            DataHora = retVal.Body.DataHora;
            Erros = retVal.Body.Erros;
            return retVal.Body.ProcessamentoOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse> ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.AdicionarConfirmacaoTicketAsync(ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest request) {
            return base.Channel.AdicionarConfirmacaoTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketResponse> AdicionarConfirmacaoTicketAsync(string TokenAutenticacao, string InterfaceIntegracao, string Versao, long CodigoTicket, ServicioIntegracion.PadraoPruebas.ArrayOfConfirmacaoDocumento Documentos) {
            ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest inValue = new ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequest();
            inValue.Body = new ServicioIntegracion.PadraoPruebas.AdicionarConfirmacaoTicketRequestBody();
            inValue.Body.TokenAutenticacao = TokenAutenticacao;
            inValue.Body.InterfaceIntegracao = InterfaceIntegracao;
            inValue.Body.Versao = Versao;
            inValue.Body.CodigoTicket = CodigoTicket;
            inValue.Body.Documentos = Documentos;
            return ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).AdicionarConfirmacaoTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioIntegracion.PadraoPruebas.ImportarDadosResponse ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.ImportarDados(ServicioIntegracion.PadraoPruebas.ImportarDadosRequest request) {
            return base.Channel.ImportarDados(request);
        }
        
        public ServicioIntegracion.PadraoPruebas.RetornoImportacao ImportarDados(string tokenAutenticacao, string interfaceIntegracao, string versao, string CodigoTicket, string Ticket) {
            ServicioIntegracion.PadraoPruebas.ImportarDadosRequest inValue = new ServicioIntegracion.PadraoPruebas.ImportarDadosRequest();
            inValue.tokenAutenticacao = tokenAutenticacao;
            inValue.interfaceIntegracao = interfaceIntegracao;
            inValue.versao = versao;
            inValue.CodigoTicket = CodigoTicket;
            inValue.Ticket = Ticket;
            ServicioIntegracion.PadraoPruebas.ImportarDadosResponse retVal = ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).ImportarDados(inValue);
            return retVal.IntegracaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ImportarDadosResponse> ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap.ImportarDadosAsync(ServicioIntegracion.PadraoPruebas.ImportarDadosRequest request) {
            return base.Channel.ImportarDadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioIntegracion.PadraoPruebas.ImportarDadosResponse> ImportarDadosAsync(string tokenAutenticacao, string interfaceIntegracao, string versao, string CodigoTicket, string Ticket) {
            ServicioIntegracion.PadraoPruebas.ImportarDadosRequest inValue = new ServicioIntegracion.PadraoPruebas.ImportarDadosRequest();
            inValue.tokenAutenticacao = tokenAutenticacao;
            inValue.interfaceIntegracao = interfaceIntegracao;
            inValue.versao = versao;
            inValue.CodigoTicket = CodigoTicket;
            inValue.Ticket = Ticket;
            return ((ServicioIntegracion.PadraoPruebas.WSIntegracaoPadraoSoap)(this)).ImportarDadosAsync(inValue);
        }
    }
}
