//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8670
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gera.com.br/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gera.com.br/", IsNullable=true)]
public partial class ArrayOfMovimentacaoEstoquePadraoERPIn_v1 {
    
    private MovimentacaoEstoquePadraoERPIn_v1[] estoqueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Estoque", IsNullable=true)]
    public MovimentacaoEstoquePadraoERPIn_v1[] Estoque {
        get {
            return this.estoqueField;
        }
        set {
            this.estoqueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gera.com.br/")]
public partial class MovimentacaoEstoquePadraoERPIn_v1 {
    
    private string codigoEstoqueField;
    
    private string codigoMaterialSKUField;
    
    private string tipoMovimentoField;
    
    private int quantidadeField;
    
    private string observacaoField;
    
    /// <comentarios/>
    public string CodigoEstoque {
        get {
            return this.codigoEstoqueField;
        }
        set {
            this.codigoEstoqueField = value;
        }
    }
    
    /// <comentarios/>
    public string CodigoMaterialSKU {
        get {
            return this.codigoMaterialSKUField;
        }
        set {
            this.codigoMaterialSKUField = value;
        }
    }
    
    /// <comentarios/>
    public string TipoMovimento {
        get {
            return this.tipoMovimentoField;
        }
        set {
            this.tipoMovimentoField = value;
        }
    }
    
    /// <comentarios/>
    public int Quantidade {
        get {
            return this.quantidadeField;
        }
        set {
            this.quantidadeField = value;
        }
    }
    
    /// <comentarios/>
    public string Observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}
